DROP TABLE IF EXISTS `sensorNode1`;
DROP TABLE IF EXISTS `sensorNode2`;
DROP TABLE IF EXISTS `sensorNode3`;
DROP TABLE IF EXISTS `sensorNode4`;
DROP TABLE IF EXISTS `sensorNode5`;
DROP TABLE IF EXISTS `sensorNode6`;
DROP TABLE IF EXISTS `sensorNode7`;
DROP TABLE IF EXISTS `sensorNode8`;
DROP TABLE IF EXISTS `sensorNode9`;
DROP TABLE IF EXISTS `sensorNode10`;

CREATE TABLE sensorNode1 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode2 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode3 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode4 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode5 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode6 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode7 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode8 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode9 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);

CREATE TABLE sensorNode10 (
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	Topic VARCHAR(50),
	Data FLOAT(5),
	PRIMARY KEY (id)
);